#!/bin/bash

# ------------------------
# System Information Report
# ------------------------

# Capture date and basic identifiers
HOSTNAME=$(hostname)
USERNAME=$(whoami)
DATE=$(date +"%Y-%m-%d %H:%M:%S")

# Load OS release info
source /etc/os-release
OS="$NAME $VERSION"

# Uptime
UPTIME=$(uptime -p)

# CPU Info
CPU=$(lshw -class processor 2>/dev/null | grep "product:" | head -n1 | awk -F: '{print $2}' | sed 's/^ *//')

# RAM Info
RAM=$(free -h | awk '/^Mem:/ {print $2}')

# Disks Info
DISKS=$(lshw -class disk 2>/dev/null | grep -E "product:|size:" | paste - - | sed 's/^[[:space:]]*//' | sed 's/ *product: //; s/ *size: / - /')

# Video Card
VIDEO=$(lshw -class display 2>/dev/null | grep "product:" | awk -F: '{print $2}' | sed 's/^ *//' | head -n1)

# Host IP Address (connected to default gateway)
DEFAULT_IF=$(ip route | awk '/default/ {print $5}' | head -n1)
IP_ADDR=$(ip -o -4 addr show "$DEFAULT_IF" 2>/dev/null | awk '{print $4}' | cut -d/ -f1)

# Gateway IP
GATEWAY=$(ip route | awk '/default/ {print $3}' | head -n1)

# DNS Servers
DNS=$(grep "nameserver" /etc/resolv.conf | awk '{print $2}' | paste -sd ", " -)

# Users Logged In
USERS=$(who | awk '{print $1}' | sort | uniq | paste -sd "," -)

# Disk Space
DISK_SPACE=$(df -h --output=target,avail | awk 'NR>1 {print $1 ": " $2}' | paste -sd ", " -)

# Process Count
PROCESS_COUNT=$(ps -e --no-headers | wc -l)

# Load Averages
LOAD_AVG=$(uptime | awk -F'load average:' '{print $2}' | sed 's/^ //')

# Listening Ports
PORTS=$(ss -tuln | awk 'NR>1 {print $5}' | awk -F: '{print $NF}' | grep -E '^[0-9]+$' | sort -n | uniq | paste -sd ", " -)

# UFW Status
if command -v ufw >/dev/null 2>&1; then
    UFW_STATUS=$(sudo ufw status 2>/dev/null | head -n1)
else
    UFW_STATUS="UFW not installed"
fi

# Output the report
cat <<EOF

System Report for $HOSTNAME generated by $USERNAME, on $DATE

System Information
------------------
OS: $OS
Uptime: $UPTIME
CPU: $CPU
RAM: $RAM
Disk(s):
$DISKS
Video: $VIDEO
Host Address: $IP_ADDR
Gateway IP: $GATEWAY
DNS Server: $DNS

System Status
-------------
Users Logged In: $USERS
Disk Space: $DISK_SPACE
Process Count: $PROCESS_COUNT
Load Averages: $LOAD_AVG
Listening Network Ports: $PORTS
UFW Status: $UFW_STATUS

EOF
